"""Add created_at and updated_at indexes

Revision ID: f462524d35a5
Revises: 904ece800e95
Create Date: 2026-01-31 15:13:13.347343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f462524d35a5'
down_revision = '904ece800e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_updated_at'))
        batch_op.drop_index(batch_op.f('ix_expense_created_at'))

    # ### end Alembic commands ###
